source 'https://github.com/CocoaPods/Specs.git'

target 'SPXSubscripting', :exclusive => true do
  pod "SPXSubscripting", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SPXSubscripting", :path => "../"

  
end
